# Dependencies
# markdown:         redcarpet
# pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Lyndon Codes
tagline:          'Lyndon Armitage\s Coding Blog'
description:      'Small blog containing code related posts by Lyndon Armitage'
url:              https://lyndon.codes
lang:             en_GB
exclude:          ["_config.yml", "README.md", "CNAME", "serve.sh", "Gemfile", "Gemfile.lock"]
comments_url:     'https://staticman.lyndon.codes/v2/entry/LyndonArmitage/lyndonarmitage.github.io/master/comments'
enable_comments:  true

author:
  name:           'Lyndon Armitage'
  email:          'lyndon.armitage@gmail.com'
  url:            https://twitter.com/LyndonArmitage
  twitter:        https://twitter.com/LyndonArmitage
  github:         https://github.com/LyndonArmitage
  linkedin:       https://www.linkedin.com/in/lyndonarmitage
  mastodon:       https://fosstodon.org/@lyndon

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/lyndonarmitage/lyndonarmitage.github.io

social:
  name: Lyndon Armitage
  links:
    - https://twitter.com/LyndonArmitage
    - https://github.com/LyndonArmitage
    - https://www.linkedin.com/in/lyndonarmitage
    - https://fosstodon.org/@lyndon
twitter:
  username: LyndonArmitage
  card: summary

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
